realms/modules/wiki/models.py
import os
import posixpath
import re
import ghdiff
import gittle.utils
import yaml
from gittle import Gittle
from dulwich.repo import NotGitRepository
from realms.lib.util import to_canonical, cname_to_filename, filename_to_cname
from realms import cache
from realms.lib.hook import HookMixin


class PageNotFound(Exception):
    pass


class Wiki(HookMixin):
    path = None
    base_path = '/'
    default_ref = 'master'
    default_committer_name = 'Anon'
    default_committer_email = 'anon@anon.anon'
    index_page = 'home'
    gittle = None
    repo = None

    def __init__(self, path):
        try:
            self.gittle = Gittle(path)
        except NotGitRepository:
            self.gittle = Gittle.init(path)

        # Dulwich repo
        self.repo = self.gittle.repo

        self.path = path

    def __repr__(self):
        return "Wiki: %s" % self.path

    def _get_user(self, username, email):
        if not username:
            username = self.default_committer_name

        if not email:
            email = self.default_committer_email

        return username, email

    def _cache_key(self, name, sha='HEAD'):
        return 'page/%s[%s]' % (name, sha)

    def revert_page(self, name, commit_sha, message, username, email):
        """Revert page to passed commit sha1

        :param name:  Name of page to revert.
        :param commit_sha: Commit Sha1 to revert to.
        :param message: Commit message.
        :param username: Committer name.
        :param email: Committer email.
        :return: Git commit sha1

        """
        page = self.get_page(name, commit_sha)
        if not page:
            raise PageNotFound('Commit not found')

        if not message:
            commit_info = gittle.utils.git.commit_info(self.gittle[commit_sha.encode('latin-1')])
            message = commit_info['message']

        return self.write_page(name, page['data'], message=message, username=username, email=email)

    def write_page(self, name, content, message=None, create=False, username=None, email=None):
        """Write page to git repo

        :param name: Name of page.
        :param content: Content of page.
        :param message: Commit message.
        :param create: Perform git add operation?
        :param username: Commit Name.
        :param email: Commit Email.
        :return: Git commit sha1.
        """

        cname = to_canonical(name)
        filename = cname_to_filename(cname)
        dirname = posixpath.join(self.path, posixpath.dirname(filename))

        if not os.path.exists(dirname):
            os.makedirs(dirname)

        with open(self.path + "/" + filename, 'w') as f:
            f.write(content)

        if create:
            self.gittle.add(filename)

        if not message:
            message = "Updated %s" % name

        username, email = self._get_user(username, email)

        ret = self.gittle.commit(name=username,
                                 email=email,
                                 message=message,
                                 files=[filename])

        cache.delete(self._cache_key(cname))

        return ret

    def rename_page(self, old_name, new_name, username=None, email=None, message=None):
        """Rename page.

        :param old_name: Page that will be renamed.
        :param new_name: New name of page.
        :param username: Committer name
        :param email: Committer email
        :return: str -- Commit sha1

        """
        old_filename, new_filename = map(cname_to_filename, [old_name, new_name])
        if old_filename not in self.gittle.index:
            # old doesn't exist
            return None

        if old_filename == new_filename:
            return

        if new_filename in self.gittle.index:
            # file is being overwritten, but that is ok, it's git!
            pass

        username, email = self._get_user(username, email)

        if not message:
            message = "Moved %s to %s" % (old_name, new_name)

        os.rename(os.path.join(self.path, old_filename), os.path.join(self.path, new_filename))

        self.gittle.add(new_filename)
        self.gittle.rm(old_filename)

        commit = self.gittle.commit(name=username,
                                    email=email,
                                    message=message,
                                    files=[old_filename, new_filename])

        cache.delete_many(self._cache_key(old_name), self._cache_key(new_name))

        return commit

    def delete_page(self, name, username=None, email=None, message=None):
        """Delete page.
        :param name: Page that will be deleted
        :param username: Committer name
        :param email: Committer email
        :return: str -- Commit sha1

        """

        username, email = self._get_user(username, email)

        if not message:
            message = "Deleted %s" % name

        filename = cname_to_filename(name)

        # gittle.rm won't actually remove the file, have to do it ourselves
        os.remove(os.path.join(self.path, filename))
        self.gittle.rm(filename)
        commit = self.gittle.commit(name=username,
                                    email=email,
                                    message=message,
                                    files=[filename])
        cache.delete_many(self._cache_key(name))
        return commit

    def get_page(self, name, sha='HEAD'):
        """Get page data, partials, commit info.

        :param name: Name of page.
        :param sha: Commit sha.
        :return: dict

        """
        cached = cache.get(self._cache_key(name, sha))
        if cached:
            return cached

        # commit = gittle.utils.git.commit_info(self.repo[sha])
        filename = cname_to_filename(name).encode('utf8')
        sha = sha.encode('latin-1')

        try:
            data = self.gittle.get_commit_files(sha, paths=[filename]).get(filename)
            if not data:
                return None
            partials = {}
            if data.get('data'):
                meta = self.get_meta(data['data'])
                if meta and 'import' in meta:
                    for partial_name in meta['import']:
                        partials[partial_name] = self.get_page(partial_name)
            data['partials'] = partials
            data['info'] = self.get_history(name, limit=1)[0]
            cache.set(self._cache_key(name, sha), data)
            return data

        except KeyError:
            # HEAD doesn't exist yet
            return None

    def get_meta(self, content):
        """Get metadata from page if any.

        :param content: Page content
        :return: dict

        """
        if not content.startswith("---"):
            return None

        meta_end = re.search("\n(\.{3}|\-{3})", content)

        if not meta_end:
            return None

        try:
            return yaml.safe_load(content[0:meta_end.start()])
        except Exception as e:
            return {'error': e.message}

    def compare(self, name, old_sha, new_sha):
        """Compare two revisions of the same page.

        :param name: Name of page.
        :param old_sha: Older sha.
        :param new_sha: Newer sha.
        :return: str - Raw markup with styles

        """

        # TODO: This could be effectively done in the browser
        old = self.get_page(name, sha=old_sha)
        new = self.get_page(name, sha=new_sha)
        return ghdiff.diff(old['data'], new['data'])

    def get_index(self):
        """Get repo index of head.

        :return: list -- List of dicts

        """
        rv = []
        index = self.repo.open_index()
        for name in index:
            rv.append(dict(name=filename_to_cname(name),
                           filename=name,
                           ctime=index[name].ctime[0],
                           mtime=index[name].mtime[0],
                           sha=index[name].sha,
                           size=index[name].size))

        return rv

    def get_history(self, name, limit=100):
        """Get page history.

        :param name: Name of page.
        :param limit: Limit history size.
        :return: list -- List of dicts

        """
        if not len(self.repo.open_index()):
            # Index is empty, no commits
            return []

        file_path = cname_to_filename(name)
        versions = []

        walker = self.repo.get_walker(paths=[file_path], max_entries=limit)
        for entry in walker:
            change_type = None
            for change in entry.changes():
                if change.old.path == file_path:
                    change_type = change.type
                elif change.new.path == file_path:
                    change_type = change.type
            author_name, author_email = entry.commit.author.rstrip('>').split('<')
            versions.append(dict(
                author=author_name.strip(),
                author_email=author_email,
                time=entry.commit.author_time,
                message=entry.commit.message,
                sha=entry.commit.id,
                type=change_type))

        return versions

realms/modules/wiki/__init__.py
import os
import sys
from realms.modules.wiki.models import Wiki


def init(app):
    # Init Wiki
    Wiki(app.config['WIKI_PATH'])

    # Check paths
    for mode in [os.W_OK, os.R_OK]:
        for dir_ in [app.config['WIKI_PATH'], os.path.join(app.config['WIKI_PATH'], '.git')]:
            if not os.access(dir_, mode):
                sys.exit('Read and write access to WIKI_PATH is required (%s)' % dir_)

realms/modules/wiki/views.py
import itertools
import sys
from flask import abort, g, render_template, request, redirect, Blueprint, flash, url_for, current_app
from flask.ext.login import login_required, current_user
from realms.lib.util import to_canonical, remove_ext, gravatar_url
from .models import PageNotFound

blueprint = Blueprint('wiki', __name__)


@blueprint.route("/_commit/<sha>/<path:name>")
def commit(name, sha):
    if current_app.config.get('PRIVATE_WIKI') and current_user.is_anonymous():
        return current_app.login_manager.unauthorized()

    cname = to_canonical(name)

    data = g.current_wiki.get_page(cname, sha=sha)

    if not data:
        abort(404)

    return render_template('wiki/page.html', name=name, page=data, commit=sha)


@blueprint.route(r"/_compare/<path:name>/<regex('\w+'):fsha><regex('\.{2,3}'):dots><regex('\w+'):lsha>")
def compare(name, fsha, dots, lsha):
    if current_app.config.get('PRIVATE_WIKI') and current_user.is_anonymous():
        return current_app.login_manager.unauthorized()

    diff = g.current_wiki.compare(name, fsha, lsha)
    return render_template('wiki/compare.html',
                           name=name, diff=diff, old=fsha, new=lsha)


@blueprint.route("/_revert", methods=['POST'])
@login_required
def revert():
    cname = to_canonical(request.form.get('name'))
    commit = request.form.get('commit')
    message = request.form.get('message', "Reverting %s" % cname)

    if not current_app.config.get('ALLOW_ANON') and current_user.is_anonymous():
        return dict(error=True, message="Anonymous posting not allowed"), 403

    if cname in current_app.config.get('WIKI_LOCKED_PAGES'):
        return dict(error=True, message="Page is locked"), 403

    try:
        sha = g.current_wiki.revert_page(cname,
                                         commit,
                                         message=message,
                                         username=current_user.username,
                                         email=current_user.email)
    except PageNotFound as e:
        return dict(error=True, message=e.message), 404

    if sha:
        flash("Page reverted")

    return dict(sha=sha)


@blueprint.route("/_history/<path:name>")
def history(name):
    if current_app.config.get('PRIVATE_WIKI') and current_user.is_anonymous():
        return current_app.login_manager.unauthorized()

    hist = g.current_wiki.get_history(name)
    for item in hist:
        item['gravatar'] = gravatar_url(item['author_email'])
    return render_template('wiki/history.html', name=name, history=hist)


@blueprint.route("/_edit/<path:name>")
@login_required
def edit(name):
    cname = to_canonical(name)
    page = g.current_wiki.get_page(name)

    if not page:
        # Page doesn't exist
        return redirect(url_for('wiki.create', name=cname))

    name = remove_ext(page['path'])
    g.assets['js'].append('editor.js')
    return render_template('wiki/edit.html',
                           name=name,
                           content=page.get('data'),
                           info=page.get('info'),
                           sha=page.get('sha'),
                           partials=page.get('partials'))


@blueprint.route("/_create/", defaults={'name': None})
@blueprint.route("/_create/<path:name>")
@login_required
def create(name):
    cname = to_canonical(name) if name else ""
    if cname and g.current_wiki.get_page(cname):
        # Page exists, edit instead
        return redirect(url_for('wiki.edit', name=cname))

    g.assets['js'].append('editor.js')
    return render_template('wiki/edit.html',
                           name=cname,
                           content="",
                           info={})


def _get_subdir(path, depth):
    parts = path.split('/', depth)
    if len(parts) > depth:
        return parts[-2]


def _tree_index(items, path=""):
    depth = len(path.split("/"))
    items = filter(lambda x: x['name'].startswith(path), items)
    items = sorted(items, key=lambda x: x['name'])
    for subdir, items in itertools.groupby(items, key=lambda x: _get_subdir(x['name'], depth)):
        if not subdir:
            for item in items:
                yield dict(item, dir=False)
        else:
            size = 0
            ctime = sys.maxint
            mtime = 0
            for item in items:
                size += item['size']
                ctime = min(item['ctime'], ctime)
                mtime = max(item['mtime'], mtime)
            yield dict(name=path + subdir + "/",
                       mtime=mtime,
                       ctime=ctime,
                       size=size,
                       dir=True)



@blueprint.route("/_index", defaults={"path": ""})
@blueprint.route("/_index/<path:path>")
def index(path):
    if current_app.config.get('PRIVATE_WIKI') and current_user.is_anonymous():
        return current_app.login_manager.unauthorized()

    items = g.current_wiki.get_index()
    if path:
        path = to_canonical(path) + "/"

    return render_template('wiki/index.html', index=_tree_index(items, path=path), path=path)


@blueprint.route("/<path:name>", methods=['POST', 'PUT', 'DELETE'])
@login_required
def page_write(name):
    cname = to_canonical(name)

    if not cname:
        return dict(error=True, message="Invalid name")

    if not current_app.config.get('ALLOW_ANON') and current_user.is_anonymous():
        return dict(error=True, message="Anonymous posting not allowed"), 403

    if request.method == 'POST':
        # Create
        if cname in current_app.config.get('WIKI_LOCKED_PAGES'):
            return dict(error=True, message="Page is locked"), 403

        sha = g.current_wiki.write_page(cname,
                                        request.form['content'],
                                        message=request.form['message'],
                                        create=True,
                                        username=current_user.username,
                                        email=current_user.email)

    elif request.method == 'PUT':
        edit_cname = to_canonical(request.form['name'])

        if edit_cname in current_app.config.get('WIKI_LOCKED_PAGES'):
            return dict(error=True, message="Page is locked"), 403

        if edit_cname != cname:
            g.current_wiki.rename_page(cname, edit_cname)

        sha = g.current_wiki.write_page(edit_cname,
                                        request.form['content'],
                                        message=request.form['message'],
                                        username=current_user.username,
                                        email=current_user.email)

        return dict(sha=sha)

    elif request.method == 'DELETE':
        # DELETE
        if cname in current_app.config.get('WIKI_LOCKED_PAGES'):
            return dict(error=True, message="Page is locked"), 403

        sha = g.current_wiki.delete_page(cname,
                                         username=current_user.username,
                                         email=current_user.email)

    return dict(sha=sha)


@blueprint.route("/", defaults={'name': 'home'})
@blueprint.route("/<path:name>")
def page(name):
    if current_app.config.get('PRIVATE_WIKI') and current_user.is_anonymous():
        return current_app.login_manager.unauthorized()

    cname = to_canonical(name)
    if cname != name:
        return redirect(url_for('wiki.page', name=cname))

    data = g.current_wiki.get_page(cname)

    if data:
        return render_template('wiki/page.html', name=cname, page=data, partials=data.get('partials'))
    else:
        return redirect(url_for('wiki.create', name=cname))

realms/templates/wiki/compare.html
{% extends 'layout.html' %}
{% block body %}

  <h2>History for <strong>{{ name }}</strong></h2>
  <div class="pull-right">
    <a href="{{ url_for('wiki.commit', name=name, sha=old) }}" class="btn btn-default btn-sm">View Old</a>
    <a href="{{ url_for('wiki.commit', name=name, sha=new) }}" class="btn btn-info btn-sm">View New</a>
  </div>
  <p>
    <a class="btn btn-default btn-sm" href="{{ url_for('wiki.history', name=name) }}">Back to History</a>
  </p>
  {{ diff|safe }}
  <p>
    <a class="btn btn-default btn-sm" href="{{ url_for('wiki.history', name=name) }}">Back to History</a>
  </p>
{% endblock %}

realms/templates/wiki/edit.html
{% extends 'layout.html' %}
{% block js %}
  <script>
    var Commit = {};
    Commit.info = {{ info|tojson }};

    var PAGE_NAME = '{{ name }}';
  </script>
  <script src="{{ url_for('static', filename='js/editor.js') }}"></script>

  {% if partials %}
    <script>
      $(function() {
        {% for name, value in partials.items() %}
          {% if name and value %}
            try {
              Handlebars.registerPartial({{ name|tojson|safe }}, {{ value.data|tojson|safe }});
            } catch (e) {
              // no data?
            }
          {% endif %}
        {% endfor %}
      });
    </script>
  {% endif %}

  {% if config.get('COLLABORATION') %}
    <script src="{{ url_for('static', filename='js/collaboration/main.js') }}"></script>
  {% endif %}

  {% if config.get('COLLABORATION') == 'firepad' %}
    <script>
      Config['FIREBASE_HOSTNAME'] = {{ config.get('FIREBASE_HOSTNAME')|tojson }};
    </script>
    <script src="https://cdn.firebase.com/js/client/1.0.17/firebase.js"></script>
    <script src="https://cdn.firebase.com/libs/firepad/1.0.0/firepad.min.js"></script>
    <script src="{{ url_for('static', filename='js/collaboration/firepad.js') }}"></script>
  {% endif %}

  {% if config.get('COLLABORATION') == 'togetherjs' %}
    <script src="{{ url_for('static', filename='js/collaboration/togetherjs.js') }}"></script>
    <script src="https://togetherjs.com/togetherjs-min.js"></script>
  {% endif %}

{% endblock %}

{% block body %}
  <div id="app-wrap">
    <div id="app-controls" class="row">
      <div class="col-xs-4 col-md-3">
        <input id="page-name" type="text" class="form-control input-sm" name="name"
               placeholder="Name" value="{{- name -}}" />
      </div>
      <div class="col-xs-4 col-md-3">
        <input id="page-message" type="text" class="form-control input-sm" name="page-message"
               placeholder="Comment" value="" />
      </div>

      <div class="col-md-6 col-xs-4 text-right">

        {% if config.get('COLLABORATION') %}
          <div class="btn-group">
            <button style='display:none' class="btn btn-danger btn-sm" id="end-collaboration">
              <i class="fa fa-comments-o"></i>
              <span class="hidden-xs">End Collaboration</span>
            </button>
          </div>
          <div class="btn-group">
            <button style='display:none' class="btn btn-default btn-sm" id="loading-collaboration" type="button">
              <i class="fa fa-cog fa-spin"></i>
              <span class="hidden-xs">Loading</span>
            </button>
          </div>
        {% endif %}

        <div class="dropdown btn-group">
          <button class="btn btn-default btn-sm dropdown-toggle" type="button" id="editor-actions"
                  data-toggle="dropdown" title="Actions">
            <i class="fa fa-cog"></i>
            <span class="hidden-xs hidden-sm">Actions <i class="fa fa-caret-down"></i></span>
          </button>

          <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="editor-actions">
            {% if config.get('COLLABORATION') %}
              <li role="presentation">
                <a role="menuitem" tabindex="-1" href="#" id="start-collaboration">Collaborate</a>
              </li>
              <li role="presentation" class="divider"></li>
            {% endif %}
            <li role="presentation">
              <a role="menuitem" tabindex="-1" href="#" id="discard-draft-btn">Delete Draft</a>
            </li>
            <li role="presentation">
              <a role="menuitem" tabindex="-1" href="#" id="delete-page-btn">Delete Page</a>
            </li>
          </ul>
        </div>

        <div class="dropdown btn-group">
          <button id="theme-list-btn" type="button" class="dropdown-toggle btn btn-default btn-sm"
                  data-toggle="dropdown" title="Change Theme">
            <i class="fa fa-paint-brush"></i>
            <span class="hidden-xs hidden-sm">Theme <i class="fa fa-caret-down"></i></span>
          </button>
          <ul id="theme-list" class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="theme-list">
            <li><a tabindex="-1" href="#" data-value="chrome" >Chrome</a></li>
            <li><a tabindex="-1" href="#" data-value="clouds" >Clouds</a></li>
            <li><a tabindex="-1" href="#" data-value="clouds_midnight" >Clouds Midnight</a></li>
            <li><a tabindex="-1" href="#" data-value="cobalt" >Cobalt</a></li>
            <li><a tabindex="-1" href="#" data-value="crimson_editor" >Crimson Editor</a></li>
            <li><a tabindex="-1" href="#" data-value="dawn" class="selected">Dawn</a></li>
            <li><a tabindex="-1" href="#" data-value="dreamweaver" >Dreamweaver</a></li>
            <li><a tabindex="-1" href="#" data-value="eclipse" >Eclipse</a></li>
            <li><a tabindex="-1" href="#" data-value="idle_fingers" >idleFingers</a></li>
            <li><a tabindex="-1" href="#" data-value="kr_theme" >krTheme</a></li>
            <li><a tabindex="-1" href="#" data-value="merbivore" >Merbivore</a></li>
            <li><a tabindex="-1" href="#" data-value="merbivore_soft" >Merbivore Soft</a></li>
            <li><a tabindex="-1" href="#" data-value="mono_industrial" >Mono Industrial</a></li>
            <li><a tabindex="-1" href="#" data-value="monokai" >Monokai</a></li>
            <li><a tabindex="-1" href="#" data-value="pastel_on_dark">Pastel on Dark</a></li>
            <li><a tabindex="-1" href="#" data-value="solarized_dark" >Solarized Dark</a></li>
            <li><a tabindex="-1" href="#" data-value="solarized_light" >Solarized Light</a></li>
            <li><a tabindex="-1" href="#" data-value="textmate" >TextMate</a></li>
            <li><a tabindex="-1" href="#" data-value="tomorrow" >Tomorrow</a></li>
            <li><a tabindex="-1" href="#" data-value="tomorrow_night">Tomorrow Night</a></li>
            <li><a tabindex="-1" href="#" data-value="tomorrow_night_blue" >Tomorrow Night Blue</a></li>
            <li><a tabindex="-1" href="#" data-value="tomorrow_night_bright" >Tomorrow Night Bright</a></li>
            <li><a tabindex="-1" href="#" data-value="tomorrow_night_eighties" >Tomorrow Night 80s</a></li>
            <li><a tabindex="-1" href="#" data-value="twilight" >Twilight</a></li>
            <li><a tabindex="-1" href="#" data-value="vibrant_ink" >Vibrant Ink</a></li>
          </ul>
        </div>

        <div class="btn-group">

          {% if name in config['WIKI_LOCKED_PAGES'] %}
            <a class="btn btn-danger btn-sm">
              <i class="fa fa-lock"></i>
              <span class="hidden-xs">Locked</span>
            </a>
          {% else %}
            <a id="submit-btn" class="btn btn-primary btn-sm">
              <i class="fa fa-save"></i>
              <span class="hidden-xs">Save</span>
            </a>
          {% endif %}
        </div>

      </div>
    </div>

    <section class="entry-markdown active">
      <header class="floatingheader" id="entry-markdown-header">
        <small>Markdown</small>
        <a class="markdown-help" href=""><span class="hidden">What is Markdown?</span></a>
      </header>
      <section id="entry-markdown-content" class="entry-markdown-content">
        <div id="editor-{{ name | b64encode }}" data-submitbtn='submit-btn' data-themeselect="theme-list" data-mode="markdown"
             data-preview="preview" class="editor">{{ content }}</div>
      </section>
    </section>

    <section class="entry-preview">
      <header class="floatingheader" id="entry-preview-header">
        <small>Preview</small>
      </header>
      <section class="entry-preview-content">
        <div id="preview"></div>
      </section>
    </section>

  </div>

{% endblock %}

realms/templates/wiki/history.html
{% extends 'layout.html' %}
{% block body %}

  <h2>History for <strong>{{ name }}</strong></h2>
  <p>
    <a class="btn btn-default btn-sm compare-revisions">Compare Revisions</a>
  </p>

  <table class="table table-bordered revision-tbl">
    <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Revision Message</th>
      <th>Date</th>
    </tr>
    </thead>
    {% for h in history %}
      <tr>
        <td class="checkbox-cell text-center">
          {% if h.type != 'delete' %}
          <input type="checkbox" name="versions[]" value="{{ h.sha }}" />
          {% endif %}
        </td>
        <td><img src="{{ h.gravatar }}?s=20" class="avatar"/> {{ h.author }}</td>
        <td><a href="{{ url_for('wiki.commit', name=name, sha=h.sha) }}" class='label label-primary'>View</a> {{ h.message }} </td>
        <td>{{ h.time|datetime }}</td>
      </tr>
    {% endfor %}
  </table>
  <p>
    <a class="btn btn-default btn-sm compare-revisions">Compare Revisions</a>
  </p>

{% endblock %}

{% block js %}
  <script>
    $(function(){
      $('.revision-tbl :checkbox').change(function () {
        var $cs=$(this).closest('.revision-tbl').find(':checkbox:checked');
        if ($cs.length > 2) {
          this.checked=false;
        }
      });

      $(".compare-revisions").click(function(){
        var $cs = $('.revision-tbl').find(':checkbox:checked');
        if ($cs.length != 2) return;
        var revs = [];
        $.each($cs, function(i, v){
          revs.push(v.value);
        });
        revs.reverse();
        revs = revs.join("..");
        location.href = "{{ config.RELATIVE_PATH }}/_compare/{{ name }}/" + revs;
      });
    });
  </script>
{% endblock %}

realms/templates/wiki/index.html
{% extends 'layout.html' %}

{% block js %}
<script>
$(document).ready(function() {
    $('.data-table').dataTable({'aaSorting': [[0, "asc"], [1, "asc"]]});
});
</script>
{% endblock %}

{% block body %}
  <h2>Index of <a href="{{ url_for('wiki.index') }}">/</a>
    {%- set parts = path.split('/') -%}
    {%- for dir in parts if dir -%}
      <a href="{{ url_for('wiki.index', path='/'.join(parts[:loop.index])) }}">{{ dir }}/</a>
    {%- endfor -%}
  </h2>
  <table class="table table-bordered data-table">
    <thead>
    <tr>
      <th style="width: 1px;"></th>
      <th>Name</th>
      <th class="hidden-xs">Bytes</th>
      <th class="hidden-xs hidden-sm">Created</th>
      <th>Modified</th>
    </tr>
    </thead>
    {% for file in index %}
      <tr>
      {% if file['dir'] %}
        <td><i class="fa fa-folder-open-o"><span style="display:none;">Dir</span></i></td>
        <td><a href="{{ url_for('wiki.index', path=file['name']) }}">{{ file['name'][path|length:] }}</a></td>
      {% else %}
        <td><i class="fa fa-file-text-o"><span style="display:none;">Page</span></i></td>
        <td><a href="{{ url_for('wiki.page', name=file['name']) }}">{{ file['name'][path|length:] }}</a></td>
      {% endif %}
        <td class="hidden-xs">{{ file['size'] }}</td>
        <td>{{ file['ctime']|datetime }}</td>
        <td class="hidden-xs hidden-sm">{{ file['mtime']|datetime }}</td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

realms/templates/wiki/page.html
{% extends 'layout.html' %}
{% block page_menu %}
  <div class="controls pull-right">
    <a class="btn btn-default btn-sm" href="{{ url_for('wiki.edit', name=name) }}">Edit</a>
    <a class="btn btn-default btn-sm" href="{{ url_for('wiki.history', name=name) }}">History</a>
  </div>
{% endblock %}

{% block body %}
  {% if commit %}
    <div id="page-action-bar">
      <form method="POST" action="{{ url_for('wiki.revert') }}" class="ajax-form" data-redirect="{{ url_for('wiki.page', name=name) }}">
        <input type="hidden" value="{{ name }}" name="name" />
        <input type="hidden" value="{{ commit }}" name="commit" />
        <input type="submit" class="btn btn-danger btn-sm" title="Revert back to this revision" value="Revert" />
      </form>
    </div>
  {% endif %}
  <div id="page-content"></div>

{% endblock %}

{% block js %}
  <script>
    $(function(){
      {% if partials %}
        {% for name, value in partials.items() %}
          Handlebars.registerPartial({{ name|tojson|safe }}, {{ value.data|tojson|safe }});
        {% endfor %}
      {% endif %}
      $("#page-content").html(MDR.convert({{ page.data|tojson|safe }})).show();
    });
  </script>
{% endblock %}